app:
  jwt:
    secret: "b2f8e1c7a9d4e6f3b7c2a1e9d8f6b3c7e1a9d4e6f3b7c2a1e9d8f6b3c7e1a9d4e6f3b7c2a1e9d8f6b3c7e1a9d4e6f3"
    expiration: 86400000

task:
  execution:
    pool:
      core-size: 2
      max-size: 10
      queue-capacity: 100
    thread-name-prefix: Async-Email-

spring:
  datasource:
    url: jdbc:postgresql://db.crqhiarrijdsltholbzr.supabase.co:5432/postgres
    username: postgres
    password: Shubham@6888
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: financeapp587@gmail.com
    password: pryqihfnzaqjwytg
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: trueō

server:
  port: 8080

