name: Gradle CI Build

# 1. Define the Trigger
on:
  push:
    branches: [ main ] # This ensures the workflow only runs when pushing to 'main'

# 2. Define the Jobs
jobs:
  build:
    runs-on: ubuntu-latest # Use a standard runner

    steps:
      # A. Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # B. Set up Java Environment
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Specify your required Java version
          distribution: 'temurin' # Use a reliable distribution like Temurin
          cache: 'gradle' # Cache Gradle dependencies for faster builds

      # C. Run the Gradle Build Command
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # Ensure the Gradle wrapper is executable

      - name: Build with Gradle
        # The '--no-daemon' flag is often used in CI environments
        # The 'build' task typically includes compile, test, and jar/package
        run: ./gradlew build --no-daemon